# Generated by Django 4.2.28 on 2026-03-03 00:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0003_userhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhistory',
            unique_together={('user', 'book')},
        ),
    ]
